on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
strategy:
  matrix:
    value: ["a", "b", "c"]
jobs:
  print:
    name: 'Print stuff'
    steps:
      env:
        VALUE: ${{ matrix.value }}
      run: |
        echo "$VALUE"