on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  print:
    runs-on: ubuntu-latest
    name: 'Print stuff'
    strategy:
      matrix:
        value: ["a", "b", "c"]
    steps:
      - env:
          VALUE: ${{ matrix.value }}
        run: |
          echo "$VALUE"