on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  messages-node:
    runs-on: ubuntu-latest
    name: 'Display error message'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node -e "console.log('::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon')"
      - run: node -e "console.log('::error file=app.js,line=1,col=5,endColumn=7::Error message with \n newline')"
      - run: node -e "console.log('::error Error message with no file')" # Does not work
      - run: node -e "console.log('::error ::Error message with no file 2')"
      - run: node -e "console.log('::error file=x,line=0,col=0,endColumn=0::Error message with fake file')"
